# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pan Pieniądz
logo: "/assets/img/logo.svg"
subtitle: FIRE po mojemu
email:
description: >- # this means to ignore newlines until "baseurl:"
  Moje podejście do codziennych finansów. Pasywne dochody i
  sposoby na niezależność finansową.
baseurl: ""
minimal_mistakes_skin: default
search: true
locale: pl-PL

head_scripts:
  - https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js
  - https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-CLG68JG7XY" # Replace this with your ID, or delete
    anonymize_ip         : true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Pan Pieniądz"
  avatar : "/assets/img/logo.svg"
  bio    : "Moje podejście do codziennych finansów. Pasywne dochody i sposoby na niezależność finansową."

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "archive"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "facebook"